import Head from 'next/head';

import Header from '../components/HeaderOther';
import Footer from '../components/Footer';

function SearchResult() {
    return (
        <div>
            <Head>
                <title>Airbnb Clone | Search Result</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <div style={{ height: '100vh', backgroundColor: 'var(--white)' }}></div>

            <Footer />
        </div>
    );
}

export default SearchResult;
